services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallets
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d wallets"]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@db:5432/wallets"
    command: gunicorn -w 6 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 main:app
    ports:
      - "8080:8000"

  liquibase:
    image: liquibase/liquibase:4.23.2
    depends_on:
      - db
    volumes:
      - ./liquibase:/liquibase/changelog
    working_dir: /liquibase/changelog
    command: >
      --url=jdbc:postgresql://db:5432/wallets
      --username=user
      --password=password
      --changeLogFile=changelog.xml
      update


volumes:
  pg_data:
